version: "3.9"

services:

  app:

    build: .

    container_name: task-manager

    restart: always

    ports:
      - "9991:9991"

    volumes:
      - .:/app
      - /app/node_modules
    
    environment:
      PORT: 9991

    command: npm start